AppDebug: true   # 调试模式

HttpServer:
  Port: ":8081" # 网站运行端口号

DataBase:
  Host: "labwebdb"
#  Host: "localhost"
  Port: "3306"
  Username: "LABWEBLABWEB"
  Password: "LabWebSampleSosd23333"
  DBName: "lab_web_sample"

Redis:
  Addr: "labwebredis:6379"
#  Addr: "localhost:6379"
  Password: ""
  DB: 0

Logger:
  LogFile: "LabWeb.API.log"

Jwt:
  Secret: "lab_web_jwt_secret"
  Issuer: "fzusosdrock"
  ExpireDays: 14

Document:
  Url: "https://github.com/RockRockWhite/"